### ISSUE TITLE
Fix: Change Master Variant is not supported

### ISSUE THREAD

**Issue by ashishhk** [commercetools/sphere-node-product-csv-sync#306]
https://jira.commercetools.com/browse/SUPPORT-11482

Currently we do not fetch products to check the which variant is master variant while importing products.We have hard coded check here (https://github.com/commercetools/sphere-node-product-csv-sync/blob/master/src/coffee/validator.coffee#L213) to detect master variant which has to be real time. Like fetch product information and detect the master variant and then generate master variant action.

**Current Error** 
Error: The action 'changeMasterVariant' is not supported. Please contact the commercetools support team!
at _.filter (/app/node_modules/sphere-node-product-csv-sync/lib/import.js:629:19)
at /app/node_modules/sphere-node-product-csv-sync/node_modules/underscore/underscore.js:255:11
at Function..each..forEach (/app/node_modules/sphere-node-product-csv-sync/node_modules/underscore/underscore.js:186:9)
at Function..filter..select (/app/node_modules/sphere-node-product-csv-sync/node_modules/underscore/underscore.js:254:7)
at Import.update (/app/node_modules/sphere-node-product-csv-sync/lib/import.js:577:27)

**Reference**
- https://github.com/commercetools/express-impex/issues/731

**Comment by ashishhk** [comment]
Once Fixed, please invite @daern91 , @VineetKumarKushwaha as reviewer.

**Comment by briantomkins** [comment]
Please note this currently assumes that the masterVariant always has variant id of 1. this is also incorrect.

**Comment by nspeet** [comment]
@VineetKumarKushwaha can we please setup a meeting to discuss this ticket on google meetings?

**Comment by nspeet** [comment]
Can we assume that the customer will include a sku for each row? This will allow for us to search for the product needed.

**Comment by VineetKumarKushwaha** [comment]
@nspeet as per the documentation here https://github.com/commercetools/sphere-node-product-csv-sync#base-attributes customer can skip sku and provide other unique value.

`    -m, --matchBy [value]                      Product attribute name which will be used to match products. Possible values: id, slug, sku, <custom_attribute_name>. Default: id. Localized attribute types are not supported for <custom_attribute_name> option.
`

Also above matchBy is the key which specifies what value makes the product unique. for an instance, user can give slug as value of matchBy then **productType** and **slug** makes it unique. So you have to write a logic to check value of **matchBy**  and then get the product based on that. So it should be similar to this

````
 static mapMapper(matchBy) {
    switch (matchBy) {
      case 'id':
        return MatchUtils.mapById;
      case 'slug':
        return MatchUtils.mapBySlug;
      case 'sku':
        return MatchUtils.mapBySku;
      default:
        return MatchUtils.mapByCustomAttribute(matchBy);
    }
  }
````

if you see this section https://github.com/commercetools/sphere-node-product-csv-sync#localized-attributes ,we have csv which does not have sku at all. So we should not only rely on sku otherwise it will break for other cases.

**Comment by nspeet** [comment]
@ashishhk @VineetKumarKushwaha  This was in regards to our original discusses about running a fetch on the product information. This was the original solution proposed. ie. Can the customer in this case provide a sku each time and then we run the product fetch for uniqueness?

**Comment by nspeet** [comment]
Ashish met with us this morning and we agreed on the following solution: "Product API fetch in the validator based on sku first as the customer uses sku, then based on id existing next, then based on fetch by key."

**Comment by nspeet** [comment]
@VineetKumarKushwaha Branch with validator update: https://github.com/commercetools/sphere-node-product-csv-sync/tree/306-detect-master-variant.

**Comment by ashishhk** [comment]
If its not deployed yet, can we keep it open so the support team can see the true picture.

**Comment by VineetKumarKushwaha** [comment]
@ashishhk We have released this package but due to pipeline issue we are not able to bump this version in impex.

**Comment by ashishhk** [comment]
okie so as a CLI its working, but not in ImpEx web UI, got it.
